version: '3'

services:
  mariadb-master:
    container_name: mariadb-master
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - './db_master_data:/var/lib/mysql'
      - './master.cnf:/etc/mysql/conf.d/mysql.cnf'
    environment:
      MARIADB_ROOT_PASSWORD: 1 
    ports:
      - "3306:3306"
    networks:
      - db-stack
    mem_limit: 2G
    labels:
      app.docker.created: "Betty"
      app.docker.env: "production"
      app.docker.service: "database"

  mariadb-slave:
    container_name: mariadb-slave
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - './db_slave_data:/var/lib/mysql'
      - './slave.cnf:/etc/mysql/conf.d/mysql.cnf'
    environment:
      MARIADB_ROOT_PASSWORD: 1 
    ports:
      - "3307:3306"
    networks:
      - db-stack
    mem_limit: 2G
    labels:
      app.docker.created: "Betty"
      app.docker.env: "production"
      app.docker.service: "database"
  maxscale:
    container_name: maxscale
    image: mariadb/maxscale:latest
    restart: unless-stopped
    volumes:
      - './maxscale.cnf:/etc/maxscale.cnf'
    ports:
      - "4006:4006"
    networks:
      - db-stack
    labels:
      app.docker.created: "Betty"
      app.docker.env: "production"
      app.docker.service: "database"
networks:
  db-stack:
    name: db-stack
    driver: bridge

